name: .NET CI (Build & NUnit Tests)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            7.0.x
            6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: NUnit Tests
        run: dotnet test Lab1_Calculator.UnitTests/Lab1_Calculator.UnitTests.csproj --configuration Release --no-build --verbosity normal

      - name: Reqnroll (BDD) Tests
        run: dotnet test Lab1_Calculator.Specs/Lab1_Calculator.Specs.csproj --configuration Release --no-build --verbosity normal
